{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rscc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rscc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rscc/rscc_{{ version }}.tar.gz
  sha256: a37b36999d8ac398b47f6e9e8037bc4643a2dc47c0edaac0f8c74424a95a5983

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
    - r-formatr
    - r-highlight
    - r-igraph
    - r-tm
  run:
    - r-base
    - r-crayon
    - r-formatr
    - r-highlight
    - r-igraph
    - r-tm

test:
  commands:
    - $R -e "library('rscc')"           # [not win]
    - "\"%R%\" -e \"library('rscc')\""  # [win]

about:
  home: https://github.com/sigbertklinke/rscc
  license: GPL-3.0-only
  summary: Evaluates R source codes by variable and/or functions names. Similar source codes
    should deliver similarity coefficients near one. Since neither the frequency nor
    the order of the used names is considered, a manual inspection of the R source code
    is required to check for similarity. Possible use cases include detection of code
    clones for improving software quality and of plagiarism amongst students' assignments.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: rscc
# Type: Package
# Title: R Source Code Similarity Evaluation by Variable/Function Names
# Version: 0.2.1
# Date: 2022-01-20
# Authors@R: c(person("Sigbert", "Klinke", email="sigbert@hu-berlin.de", role=c("aut", "cre")))
# Description: Evaluates R source codes by variable and/or functions names. Similar source codes should deliver similarity coefficients near one. Since neither the frequency nor the order of the used names is considered, a manual inspection of the R source code is required to check for similarity. Possible use cases include detection of code clones for improving software quality and of plagiarism amongst students' assignments.
# License: GPL-3
# URL: https://github.com/sigbertklinke/rscc (development version)
# Imports: crayon, formatR, highlight, igraph, tm
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# Suggests: rmarkdown, knitr
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-01-20 11:31:07 UTC; sk
# Author: Sigbert Klinke [aut, cre]
# Maintainer: Sigbert Klinke <sigbert@hu-berlin.de>
# Repository: CRAN
# Date/Publication: 2022-01-20 12:02:42 UTC
